baseURL = "https://example.org/"
languageCode = "en-us"
title = "helloworld"
theme = "ananke"
resourceDir = "../resources"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  recent_posts_number = 3

  
[[params.ananke_socials]]
name = "github"
url = "https://example.org/"